/* 模拟的区县列表数据 */

export const countryList = [{
	"ID": 0,
	"DCName": "上海市",
	"CountyCode": "all"
}, {
	"ID": 1,
	"DCName": "黄浦区",
	"CountyCode": "01H"
}, {
	"ID": 2,
	"DCName": "徐汇区",
	"CountyCode": "02X"
}, {
	"ID": 3,
	"DCName": "长宁区",
	"CountyCode": "03C"
}, {
	"ID": 4,
	"DCName": "静安区",
	"CountyCode": "04J"
}, {
	"ID": 5,
	"DCName": "普陀区",
	"CountyCode": "05P"
}, {
	"ID": 6,
	"DCName": "虹口区",
	"CountyCode": "06H"
}, {
	"ID": 7,
	"DCName": "杨浦区",
	"CountyCode": "07Y"
}, {
	"ID": 8,
	"DCName": "闵行区",
	"CountyCode": "08M"
}, {
	"ID": 9,
	"DCName": "宝山区",
	"CountyCode": "09B"
}, {
	"ID": 10,
	"DCName": "嘉定区",
	"CountyCode": "10J"
}, {
	"ID": 11,
	"DCName": "浦东新区",
	"CountyCode": "11P"
}, {
	"ID": 12,
	"DCName": "金山区",
	"CountyCode": "12J"
}, {
	"ID": 13,
	"DCName": "松江区",
	"CountyCode": "13S"
}, {
	"ID": 14,
	"DCName": "青浦区",
	"CountyCode": "14Q"
}, {
	"ID": 15,
	"DCName": "奉贤区",
	"CountyCode": "15F"
}, {
	"ID": 16,
	"DCName": "崇明区",
	"CountyCode": "16C"
}]


/* 模拟的街道列表数据 */
export const streetTowns = [{
	"ID": 0,
	"MembershipCounty": "01H",
	"StreetTownName": "全部",
	"StreetTownCode": "all",
	"GroupCode": "01H01B"
}, {
	"ID": 1,
	"MembershipCounty": "01H",
	"StreetTownName": "半淞园路街道",
	"StreetTownCode": "01B",
	"GroupCode": "01H01B"
}, {
	"ID": 2,
	"MembershipCounty": "01H",
	"StreetTownName": "五里桥街道",
	"StreetTownCode": "02W",
	"GroupCode": "01H02W"
}, {
	"ID": 3,
	"MembershipCounty": "01H",
	"StreetTownName": "打浦桥街道",
	"StreetTownCode": "03D",
	"GroupCode": "01H03D"
}, {
	"ID": 4,
	"MembershipCounty": "01H",
	"StreetTownName": "小东门街道",
	"StreetTownCode": "04X",
	"GroupCode": "01H04X"
}, {
	"ID": 5,
	"MembershipCounty": "01H",
	"StreetTownName": "老西门街道",
	"StreetTownCode": "05L",
	"GroupCode": "01H05L"
}, {
	"ID": 6,
	"MembershipCounty": "01H",
	"StreetTownName": "淮海中路街道",
	"StreetTownCode": "06H",
	"GroupCode": "01H06H"
}, {
	"ID": 7,
	"MembershipCounty": "01H",
	"StreetTownName": "瑞金二路街道",
	"StreetTownCode": "07R",
	"GroupCode": "01H07R"
}, {
	"ID": 8,
	"MembershipCounty": "01H",
	"StreetTownName": "豫园街道",
	"StreetTownCode": "08Y",
	"GroupCode": "01H08Y"
}, {
	"ID": 9,
	"MembershipCounty": "01H",
	"StreetTownName": "南京东路街道",
	"StreetTownCode": "09N",
	"GroupCode": "01H09N"
}, {
	"ID": 10,
	"MembershipCounty": "01H",
	"StreetTownName": "外滩街道",
	"StreetTownCode": "10W",
	"GroupCode": "01H10W"
}, {
	"ID": 11,
	"MembershipCounty": "02X",
	"StreetTownName": "华泾镇",
	"StreetTownCode": "01H",
	"GroupCode": "02X01H"
}, {
	"ID": 12,
	"MembershipCounty": "02X",
	"StreetTownName": "长桥街道",
	"StreetTownCode": "02C",
	"GroupCode": "02X02C"
}, {
	"ID": 13,
	"MembershipCounty": "02X",
	"StreetTownName": "龙华街道",
	"StreetTownCode": "03L",
	"GroupCode": "02X03L"
}, {
	"ID": 14,
	"MembershipCounty": "02X",
	"StreetTownName": "漕河泾街道",
	"StreetTownCode": "04C",
	"GroupCode": "02X04C"
}, {
	"ID": 15,
	"MembershipCounty": "02X",
	"StreetTownName": "凌云路街道",
	"StreetTownCode": "05L",
	"GroupCode": "02X05L"
}, {
	"ID": 16,
	"MembershipCounty": "02X",
	"StreetTownName": "康健街道",
	"StreetTownCode": "06K",
	"GroupCode": "02X06K"
}, {
	"ID": 17,
	"MembershipCounty": "02X",
	"StreetTownName": "田林街道",
	"StreetTownCode": "07T",
	"GroupCode": "02X07T"
}, {
	"ID": 18,
	"MembershipCounty": "02X",
	"StreetTownName": "虹梅路街道",
	"StreetTownCode": "08H",
	"GroupCode": "02X08H"
}, {
	"ID": 19,
	"MembershipCounty": "02X",
	"StreetTownName": "斜土路街道",
	"StreetTownCode": "09X",
	"GroupCode": "02X09X"
}, {
	"ID": 20,
	"MembershipCounty": "02X",
	"StreetTownName": "枫林路街道",
	"StreetTownCode": "10F",
	"GroupCode": "02X10F"
}, {
	"ID": 21,
	"MembershipCounty": "02X",
	"StreetTownName": "徐家汇街道",
	"StreetTownCode": "11X",
	"GroupCode": "02X11X"
}, {
	"ID": 22,
	"MembershipCounty": "02X",
	"StreetTownName": "天平路街道",
	"StreetTownCode": "12T",
	"GroupCode": "02X12T"
}, {
	"ID": 23,
	"MembershipCounty": "02X",
	"StreetTownName": "湖南路街道",
	"StreetTownCode": "13H",
	"GroupCode": "02X13H"
}, {
	"ID": 24,
	"MembershipCounty": "03C",
	"StreetTownName": "新华路街道",
	"StreetTownCode": "01X",
	"GroupCode": "03C01X"
}, {
	"ID": 25,
	"MembershipCounty": "03C",
	"StreetTownName": "虹桥街道",
	"StreetTownCode": "02H",
	"GroupCode": "03C02H"
}, {
	"ID": 26,
	"MembershipCounty": "03C",
	"StreetTownName": "程家桥街道",
	"StreetTownCode": "03C",
	"GroupCode": "03C03C"
}, {
	"ID": 27,
	"MembershipCounty": "03C",
	"StreetTownName": "天山路街道",
	"StreetTownCode": "04T",
	"GroupCode": "03C04T"
}, {
	"ID": 28,
	"MembershipCounty": "03C",
	"StreetTownName": "仙霞新村街道",
	"StreetTownCode": "05X",
	"GroupCode": "03C05X"
}, {
	"ID": 29,
	"MembershipCounty": "03C",
	"StreetTownName": "新泾镇",
	"StreetTownCode": "06X",
	"GroupCode": "03C06X"
}, {
	"ID": 30,
	"MembershipCounty": "03C",
	"StreetTownName": "江苏路街道",
	"StreetTownCode": "07J",
	"GroupCode": "03C07J"
}, {
	"ID": 31,
	"MembershipCounty": "03C",
	"StreetTownName": "华阳路街道",
	"StreetTownCode": "08H",
	"GroupCode": "03C08H"
}, {
	"ID": 32,
	"MembershipCounty": "03C",
	"StreetTownName": "周家桥街道",
	"StreetTownCode": "09Z",
	"GroupCode": "03C09Z"
}, {
	"ID": 33,
	"MembershipCounty": "03C",
	"StreetTownName": "北新泾街道",
	"StreetTownCode": "10B",
	"GroupCode": "03C10B"
}, {
	"ID": 34,
	"MembershipCounty": "04J",
	"StreetTownName": "南京西路街道",
	"StreetTownCode": "01N",
	"GroupCode": "04J01N"
}, {
	"ID": 35,
	"MembershipCounty": "04J",
	"StreetTownName": "静安寺街道",
	"StreetTownCode": "02J",
	"GroupCode": "04J02J"
}, {
	"ID": 36,
	"MembershipCounty": "04J",
	"StreetTownName": "石门二路街道",
	"StreetTownCode": "03S",
	"GroupCode": "04J03S"
}, {
	"ID": 37,
	"MembershipCounty": "04J",
	"StreetTownName": "江宁路街道",
	"StreetTownCode": "04J",
	"GroupCode": "04J04J"
}, {
	"ID": 38,
	"MembershipCounty": "04J",
	"StreetTownName": "曹家渡街道",
	"StreetTownCode": "05C",
	"GroupCode": "04J05C"
}, {
	"ID": 39,
	"MembershipCounty": "04J",
	"StreetTownName": "北站街道",
	"StreetTownCode": "06B",
	"GroupCode": "04J06B"
}, {
	"ID": 40,
	"MembershipCounty": "04J",
	"StreetTownName": "宝山路街道",
	"StreetTownCode": "07B",
	"GroupCode": "04J07B"
}, {
	"ID": 41,
	"MembershipCounty": "04J",
	"StreetTownName": "芷江西路街道",
	"StreetTownCode": "08Z",
	"GroupCode": "04J08Z"
}, {
	"ID": 42,
	"MembershipCounty": "04J",
	"StreetTownName": "天目西路街道",
	"StreetTownCode": "09T",
	"GroupCode": "04J09T"
}, {
	"ID": 43,
	"MembershipCounty": "04J",
	"StreetTownName": "共和新路街道",
	"StreetTownCode": "10G",
	"GroupCode": "04J10G"
}, {
	"ID": 44,
	"MembershipCounty": "04J",
	"StreetTownName": "大宁路街道",
	"StreetTownCode": "11D",
	"GroupCode": "04J11D"
}, {
	"ID": 45,
	"MembershipCounty": "04J",
	"StreetTownName": "彭浦镇",
	"StreetTownCode": "12P",
	"GroupCode": "04J12P"
}, {
	"ID": 46,
	"MembershipCounty": "04J",
	"StreetTownName": "临汾路街道",
	"StreetTownCode": "13L",
	"GroupCode": "04J13L"
}, {
	"ID": 47,
	"MembershipCounty": "04J",
	"StreetTownName": "彭浦新村街道",
	"StreetTownCode": "14P",
	"GroupCode": "04J14P"
}, {
	"ID": 48,
	"MembershipCounty": "05P",
	"StreetTownName": "长风新村街道",
	"StreetTownCode": "01C",
	"GroupCode": "05P01C"
}, {
	"ID": 49,
	"MembershipCounty": "05P",
	"StreetTownName": "长寿路街道",
	"StreetTownCode": "02C",
	"GroupCode": "05P02C"
}, {
	"ID": 50,
	"MembershipCounty": "05P",
	"StreetTownName": "曹杨新村街道",
	"StreetTownCode": "03C",
	"GroupCode": "05P03C"
}, {
	"ID": 51,
	"MembershipCounty": "05P",
	"StreetTownName": "长征镇",
	"StreetTownCode": "04C",
	"GroupCode": "05P04C"
}, {
	"ID": 52,
	"MembershipCounty": "05P",
	"StreetTownName": "宜川路街道",
	"StreetTownCode": "05Y",
	"GroupCode": "05P05Y"
}, {
	"ID": 53,
	"MembershipCounty": "05P",
	"StreetTownName": "石泉路街道",
	"StreetTownCode": "06S",
	"GroupCode": "05P06S"
}, {
	"ID": 54,
	"MembershipCounty": "05P",
	"StreetTownName": "真如镇街道",
	"StreetTownCode": "07Z",
	"GroupCode": "05P07Z"
}, {
	"ID": 55,
	"MembershipCounty": "05P",
	"StreetTownName": "甘泉路街道",
	"StreetTownCode": "08G",
	"GroupCode": "05P08G"
}, {
	"ID": 56,
	"MembershipCounty": "05P",
	"StreetTownName": "万里街道",
	"StreetTownCode": "09W",
	"GroupCode": "05P09W"
}, {
	"ID": 57,
	"MembershipCounty": "05P",
	"StreetTownName": "桃浦镇",
	"StreetTownCode": "10T",
	"GroupCode": "05P10T"
}, {
	"ID": 58,
	"MembershipCounty": "06H",
	"StreetTownName": "提篮桥街道",
	"StreetTownCode": "01T",
	"GroupCode": "06H01T"
}, {
	"ID": 59,
	"MembershipCounty": "06H",
	"StreetTownName": "嘉兴路街道",
	"StreetTownCode": "02J",
	"GroupCode": "06H02J"
}, {
	"ID": 60,
	"MembershipCounty": "06H",
	"StreetTownName": "四川北路街道",
	"StreetTownCode": "03S",
	"GroupCode": "06H03S"
}, {
	"ID": 61,
	"MembershipCounty": "06H",
	"StreetTownName": "欧阳路街道",
	"StreetTownCode": "04O",
	"GroupCode": "06H04O"
}, {
	"ID": 62,
	"MembershipCounty": "06H",
	"StreetTownName": "曲阳路街道",
	"StreetTownCode": "05Q",
	"GroupCode": "06H05Q"
}, {
	"ID": 63,
	"MembershipCounty": "06H",
	"StreetTownName": "广中路街道",
	"StreetTownCode": "06G",
	"GroupCode": "06H06G"
}, {
	"ID": 64,
	"MembershipCounty": "06H",
	"StreetTownName": "凉城新村街道",
	"StreetTownCode": "07L",
	"GroupCode": "06H07L"
}, {
	"ID": 65,
	"MembershipCounty": "06H",
	"StreetTownName": "江湾镇街道",
	"StreetTownCode": "08J",
	"GroupCode": "06H08J"
}, {
	"ID": 66,
	"MembershipCounty": "07Y",
	"StreetTownName": "定海路街道",
	"StreetTownCode": "01D",
	"GroupCode": "07Y01D"
}, {
	"ID": 67,
	"MembershipCounty": "07Y",
	"StreetTownName": "大桥街道",
	"StreetTownCode": "02D",
	"GroupCode": "07Y02D"
}, {
	"ID": 68,
	"MembershipCounty": "07Y",
	"StreetTownName": "平凉路街道",
	"StreetTownCode": "03P",
	"GroupCode": "07Y03P"
}, {
	"ID": 69,
	"MembershipCounty": "07Y",
	"StreetTownName": "江浦路街道",
	"StreetTownCode": "04J",
	"GroupCode": "07Y04J"
}, {
	"ID": 70,
	"MembershipCounty": "07Y",
	"StreetTownName": "长白新村街道",
	"StreetTownCode": "05C",
	"GroupCode": "07Y05C"
}, {
	"ID": 71,
	"MembershipCounty": "07Y",
	"StreetTownName": "延吉新村街道",
	"StreetTownCode": "06Y",
	"GroupCode": "07Y06Y"
}, {
	"ID": 72,
	"MembershipCounty": "07Y",
	"StreetTownName": "控江路街道",
	"StreetTownCode": "07K",
	"GroupCode": "07Y07K"
}, {
	"ID": 73,
	"MembershipCounty": "07Y",
	"StreetTownName": "四平路街道",
	"StreetTownCode": "08S",
	"GroupCode": "07Y08S"
}, {
	"ID": 74,
	"MembershipCounty": "07Y",
	"StreetTownName": "五角场镇",
	"StreetTownCode": "09W",
	"GroupCode": "07Y09W"
}, {
	"ID": 75,
	"MembershipCounty": "07Y",
	"StreetTownName": "五角场街道",
	"StreetTownCode": "10W",
	"GroupCode": "07Y10W"
}, {
	"ID": 76,
	"MembershipCounty": "07Y",
	"StreetTownName": "殷行街道",
	"StreetTownCode": "11Y",
	"GroupCode": "07Y11Y"
}, {
	"ID": 77,
	"MembershipCounty": "07Y",
	"StreetTownName": "新江湾城街道",
	"StreetTownCode": "12X",
	"GroupCode": "07Y12X"
}, {
	"ID": 78,
	"MembershipCounty": "08M",
	"StreetTownName": "浦江镇",
	"StreetTownCode": "01P",
	"GroupCode": "08M01P"
}, {
	"ID": 79,
	"MembershipCounty": "08M",
	"StreetTownName": "浦锦街道",
	"StreetTownCode": "02P",
	"GroupCode": "08M02P"
}, {
	"ID": 80,
	"MembershipCounty": "08M",
	"StreetTownName": "吴泾镇",
	"StreetTownCode": "03W",
	"GroupCode": "08M03W"
}, {
	"ID": 81,
	"MembershipCounty": "08M",
	"StreetTownName": "江川路街道",
	"StreetTownCode": "04J",
	"GroupCode": "08M04J"
}, {
	"ID": 82,
	"MembershipCounty": "08M",
	"StreetTownName": "马桥镇",
	"StreetTownCode": "05M",
	"GroupCode": "08M05M"
}, {
	"ID": 83,
	"MembershipCounty": "08M",
	"StreetTownName": "颛桥镇",
	"StreetTownCode": "06Z",
	"GroupCode": "08M06Z"
}, {
	"ID": 84,
	"MembershipCounty": "08M",
	"StreetTownName": "莘庄工业园区",
	"StreetTownCode": "07X",
	"GroupCode": "08M07X"
}, {
	"ID": 85,
	"MembershipCounty": "08M",
	"StreetTownName": "梅陇镇",
	"StreetTownCode": "08M",
	"GroupCode": "08M08M"
}, {
	"ID": 86,
	"MembershipCounty": "08M",
	"StreetTownName": "莘庄镇",
	"StreetTownCode": "09X",
	"GroupCode": "08M09X"
}, {
	"ID": 87,
	"MembershipCounty": "08M",
	"StreetTownName": "古美路街道",
	"StreetTownCode": "10G",
	"GroupCode": "08M10G"
}, {
	"ID": 88,
	"MembershipCounty": "08M",
	"StreetTownName": "七宝镇",
	"StreetTownCode": "11Q",
	"GroupCode": "08M11Q"
}, {
	"ID": 89,
	"MembershipCounty": "08M",
	"StreetTownName": "虹桥镇",
	"StreetTownCode": "12H",
	"GroupCode": "08M12H"
}, {
	"ID": 90,
	"MembershipCounty": "08M",
	"StreetTownName": "新虹街道",
	"StreetTownCode": "13X",
	"GroupCode": "08M13X"
}, {
	"ID": 91,
	"MembershipCounty": "08M",
	"StreetTownName": "华漕镇",
	"StreetTownCode": "14H",
	"GroupCode": "08M14H"
}, {
	"ID": 92,
	"MembershipCounty": "09B",
	"StreetTownName": "大场镇",
	"StreetTownCode": "01D",
	"GroupCode": "09B01D"
}, {
	"ID": 93,
	"MembershipCounty": "09B",
	"StreetTownName": "高境镇",
	"StreetTownCode": "02G",
	"GroupCode": "09B02G"
}, {
	"ID": 94,
	"MembershipCounty": "09B",
	"StreetTownName": "淞南镇",
	"StreetTownCode": "03S",
	"GroupCode": "09B03S"
}, {
	"ID": 95,
	"MembershipCounty": "09B",
	"StreetTownName": "张庙街道",
	"StreetTownCode": "04Z",
	"GroupCode": "09B04Z"
}, {
	"ID": 96,
	"MembershipCounty": "09B",
	"StreetTownName": "庙行镇",
	"StreetTownCode": "05M",
	"GroupCode": "09B05M"
}, {
	"ID": 97,
	"MembershipCounty": "09B",
	"StreetTownName": "吴淞街道",
	"StreetTownCode": "06W",
	"GroupCode": "09B06W"
}, {
	"ID": 98,
	"MembershipCounty": "09B",
	"StreetTownName": "杨行镇",
	"StreetTownCode": "07Y",
	"GroupCode": "09B07Y"
}, {
	"ID": 99,
	"MembershipCounty": "09B",
	"StreetTownName": "顾村镇",
	"StreetTownCode": "08G",
	"GroupCode": "09B08G"
}, {
	"ID": 100,
	"MembershipCounty": "09B",
	"StreetTownName": "友谊路街道",
	"StreetTownCode": "09Y",
	"GroupCode": "09B09Y"
}, {
	"ID": 101,
	"MembershipCounty": "09B",
	"StreetTownName": "月浦镇",
	"StreetTownCode": "10Y",
	"GroupCode": "09B10Y"
}, {
	"ID": 102,
	"MembershipCounty": "09B",
	"StreetTownName": "罗店镇",
	"StreetTownCode": "11L",
	"GroupCode": "09B11L"
}, {
	"ID": 103,
	"MembershipCounty": "09B",
	"StreetTownName": "罗泾镇",
	"StreetTownCode": "12L",
	"GroupCode": "09B12L"
}, {
	"ID": 104,
	"MembershipCounty": "10J",
	"StreetTownName": "真新街道",
	"StreetTownCode": "01Z",
	"GroupCode": "10J01Z"
}, {
	"ID": 105,
	"MembershipCounty": "10J",
	"StreetTownName": "江桥镇",
	"StreetTownCode": "02J",
	"GroupCode": "10J02J"
}, {
	"ID": 106,
	"MembershipCounty": "10J",
	"StreetTownName": "南翔镇",
	"StreetTownCode": "03N",
	"GroupCode": "10J03N"
}, {
	"ID": 107,
	"MembershipCounty": "10J",
	"StreetTownName": "安亭镇",
	"StreetTownCode": "04A",
	"GroupCode": "10J04A"
}, {
	"ID": 108,
	"MembershipCounty": "10J",
	"StreetTownName": "马陆镇",
	"StreetTownCode": "05M",
	"GroupCode": "10J05M"
}, {
	"ID": 109,
	"MembershipCounty": "10J",
	"StreetTownName": "嘉定工业区",
	"StreetTownCode": "06J",
	"GroupCode": "10J06J"
}, {
	"ID": 110,
	"MembershipCounty": "10J",
	"StreetTownName": "新城路街道",
	"StreetTownCode": "07X",
	"GroupCode": "10J07X"
}, {
	"ID": 111,
	"MembershipCounty": "10J",
	"StreetTownName": "嘉定镇街道",
	"StreetTownCode": "08J",
	"GroupCode": "10J08J"
}, {
	"ID": 112,
	"MembershipCounty": "10J",
	"StreetTownName": "菊园新区",
	"StreetTownCode": "09J",
	"GroupCode": "10J09J"
}, {
	"ID": 113,
	"MembershipCounty": "10J",
	"StreetTownName": "外冈镇",
	"StreetTownCode": "10W",
	"GroupCode": "10J10W"
}, {
	"ID": 114,
	"MembershipCounty": "10J",
	"StreetTownName": "徐行镇",
	"StreetTownCode": "11X",
	"GroupCode": "10J11X"
}, {
	"ID": 115,
	"MembershipCounty": "10J",
	"StreetTownName": "华亭镇",
	"StreetTownCode": "12H",
	"GroupCode": "10J12H"
}, {
	"ID": 116,
	"MembershipCounty": "11P",
	"StreetTownName": "南汇新城镇",
	"StreetTownCode": "01N",
	"GroupCode": "11P01N"
}, {
	"ID": 117,
	"MembershipCounty": "11P",
	"StreetTownName": "泥城镇",
	"StreetTownCode": "02N",
	"GroupCode": "11P02N"
}, {
	"ID": 118,
	"MembershipCounty": "11P",
	"StreetTownName": "书院镇",
	"StreetTownCode": "03S",
	"GroupCode": "11P03S"
}, {
	"ID": 119,
	"MembershipCounty": "11P",
	"StreetTownName": "万祥镇",
	"StreetTownCode": "04W",
	"GroupCode": "11P04W"
}, {
	"ID": 120,
	"MembershipCounty": "11P",
	"StreetTownName": "大团镇",
	"StreetTownCode": "05D",
	"GroupCode": "11P05D"
}, {
	"ID": 121,
	"MembershipCounty": "11P",
	"StreetTownName": "老港镇",
	"StreetTownCode": "06L",
	"GroupCode": "11P06L"
}, {
	"ID": 122,
	"MembershipCounty": "11P",
	"StreetTownName": "惠南镇",
	"StreetTownCode": "07H",
	"GroupCode": "11P07H"
}, {
	"ID": 123,
	"MembershipCounty": "11P",
	"StreetTownName": "宣桥镇",
	"StreetTownCode": "08X",
	"GroupCode": "11P08X"
}, {
	"ID": 124,
	"MembershipCounty": "11P",
	"StreetTownName": "新场镇",
	"StreetTownCode": "09X",
	"GroupCode": "11P09X"
}, {
	"ID": 125,
	"MembershipCounty": "11P",
	"StreetTownName": "航头镇",
	"StreetTownCode": "10H",
	"GroupCode": "11P10H"
}, {
	"ID": 126,
	"MembershipCounty": "11P",
	"StreetTownName": "祝桥镇",
	"StreetTownCode": "11Z",
	"GroupCode": "11P11Z"
}, {
	"ID": 127,
	"MembershipCounty": "11P",
	"StreetTownName": "川沙新镇",
	"StreetTownCode": "12C",
	"GroupCode": "11P12C"
}, {
	"ID": 128,
	"MembershipCounty": "11P",
	"StreetTownName": "周浦镇",
	"StreetTownCode": "13Z",
	"GroupCode": "11P13Z"
}, {
	"ID": 129,
	"MembershipCounty": "11P",
	"StreetTownName": "康桥镇",
	"StreetTownCode": "14K",
	"GroupCode": "11P14K"
}, {
	"ID": 130,
	"MembershipCounty": "11P",
	"StreetTownName": "三林镇",
	"StreetTownCode": "15S",
	"GroupCode": "11P15S"
}, {
	"ID": 131,
	"MembershipCounty": "11P",
	"StreetTownName": "东明路街道",
	"StreetTownCode": "16D",
	"GroupCode": "11P16D"
}, {
	"ID": 132,
	"MembershipCounty": "11P",
	"StreetTownName": "张江镇",
	"StreetTownCode": "17Z",
	"GroupCode": "11P17Z"
}, {
	"ID": 133,
	"MembershipCounty": "11P",
	"StreetTownName": "北蔡镇",
	"StreetTownCode": "18B",
	"GroupCode": "11P18B"
}, {
	"ID": 134,
	"MembershipCounty": "11P",
	"StreetTownName": "周家渡街道",
	"StreetTownCode": "19Z",
	"GroupCode": "11P19Z"
}, {
	"ID": 135,
	"MembershipCounty": "11P",
	"StreetTownName": "上钢新村街道",
	"StreetTownCode": "20S",
	"GroupCode": "11P20S"
}, {
	"ID": 136,
	"MembershipCounty": "11P",
	"StreetTownName": "花木街道",
	"StreetTownCode": "21H",
	"GroupCode": "11P21H"
}, {
	"ID": 137,
	"MembershipCounty": "11P",
	"StreetTownName": "南码头路街道",
	"StreetTownCode": "22N",
	"GroupCode": "11P22N"
}, {
	"ID": 138,
	"MembershipCounty": "11P",
	"StreetTownName": "塘桥街道",
	"StreetTownCode": "23T",
	"GroupCode": "11P23T"
}, {
	"ID": 139,
	"MembershipCounty": "11P",
	"StreetTownName": "潍坊新村街道",
	"StreetTownCode": "24W",
	"GroupCode": "11P24W"
}, {
	"ID": 140,
	"MembershipCounty": "11P",
	"StreetTownName": "洋泾街道",
	"StreetTownCode": "25Y",
	"GroupCode": "11P25Y"
}, {
	"ID": 141,
	"MembershipCounty": "11P",
	"StreetTownName": "陆家嘴街道",
	"StreetTownCode": "26L",
	"GroupCode": "11P26L"
}, {
	"ID": 142,
	"MembershipCounty": "11P",
	"StreetTownName": "合庆镇",
	"StreetTownCode": "27H",
	"GroupCode": "11P27H"
}, {
	"ID": 143,
	"MembershipCounty": "11P",
	"StreetTownName": "唐镇",
	"StreetTownCode": "28T",
	"GroupCode": "11P28T"
}, {
	"ID": 144,
	"MembershipCounty": "11P",
	"StreetTownName": "曹路镇",
	"StreetTownCode": "29C",
	"GroupCode": "11P29C"
}, {
	"ID": 145,
	"MembershipCounty": "11P",
	"StreetTownName": "金桥镇",
	"StreetTownCode": "30J",
	"GroupCode": "11P30J"
}, {
	"ID": 146,
	"MembershipCounty": "11P",
	"StreetTownName": "金杨新村街道",
	"StreetTownCode": "31J",
	"GroupCode": "11P31J"
}, {
	"ID": 147,
	"MembershipCounty": "11P",
	"StreetTownName": "浦兴路街道",
	"StreetTownCode": "32P",
	"GroupCode": "11P32P"
}, {
	"ID": 148,
	"MembershipCounty": "11P",
	"StreetTownName": "沪东新村街道",
	"StreetTownCode": "33H",
	"GroupCode": "11P33H"
}, {
	"ID": 149,
	"MembershipCounty": "11P",
	"StreetTownName": "高东镇",
	"StreetTownCode": "34G",
	"GroupCode": "11P34G"
}, {
	"ID": 150,
	"MembershipCounty": "11P",
	"StreetTownName": "高行镇",
	"StreetTownCode": "35G",
	"GroupCode": "11P35G"
}, {
	"ID": 151,
	"MembershipCounty": "11P",
	"StreetTownName": "高桥镇",
	"StreetTownCode": "36G",
	"GroupCode": "11P36G"
}, {
	"ID": 152,
	"MembershipCounty": "12J",
	"StreetTownName": "石化街道",
	"StreetTownCode": "01S",
	"GroupCode": "12J01S"
}, {
	"ID": 153,
	"MembershipCounty": "12J",
	"StreetTownName": "漕泾镇",
	"StreetTownCode": "02C",
	"GroupCode": "12J02C"
}, {
	"ID": 154,
	"MembershipCounty": "12J",
	"StreetTownName": "山阳镇",
	"StreetTownCode": "03S",
	"GroupCode": "12J03S"
}, {
	"ID": 155,
	"MembershipCounty": "12J",
	"StreetTownName": "金山卫镇",
	"StreetTownCode": "04J",
	"GroupCode": "12J04J"
}, {
	"ID": 156,
	"MembershipCounty": "12J",
	"StreetTownName": "张堰镇",
	"StreetTownCode": "05Z",
	"GroupCode": "12J05Z"
}, {
	"ID": 157,
	"MembershipCounty": "12J",
	"StreetTownName": "廊下镇",
	"StreetTownCode": "06L",
	"GroupCode": "12J06L"
}, {
	"ID": 158,
	"MembershipCounty": "12J",
	"StreetTownName": "亭林镇",
	"StreetTownCode": "07T",
	"GroupCode": "12J07T"
}, {
	"ID": 159,
	"MembershipCounty": "12J",
	"StreetTownName": "吕巷镇",
	"StreetTownCode": "08L",
	"GroupCode": "12J08L"
}, {
	"ID": 160,
	"MembershipCounty": "12J",
	"StreetTownName": "朱泾镇",
	"StreetTownCode": "09Z",
	"GroupCode": "12J09Z"
}, {
	"ID": 161,
	"MembershipCounty": "12J",
	"StreetTownName": "枫泾镇",
	"StreetTownCode": "10F",
	"GroupCode": "12J10F"
}, {
	"ID": 162,
	"MembershipCounty": "13S",
	"StreetTownName": "叶榭镇",
	"StreetTownCode": "01Y",
	"GroupCode": "13S01Y"
}, {
	"ID": 163,
	"MembershipCounty": "13S",
	"StreetTownName": "泖港镇",
	"StreetTownCode": "02M",
	"GroupCode": "13S02M"
}, {
	"ID": 164,
	"MembershipCounty": "13S",
	"StreetTownName": "新浜镇",
	"StreetTownCode": "03X",
	"GroupCode": "13S03X"
}, {
	"ID": 165,
	"MembershipCounty": "13S",
	"StreetTownName": "车墩镇",
	"StreetTownCode": "04C",
	"GroupCode": "13S04C"
}, {
	"ID": 166,
	"MembershipCounty": "13S",
	"StreetTownName": "岳阳街道",
	"StreetTownCode": "05Y",
	"GroupCode": "13S05Y"
}, {
	"ID": 167,
	"MembershipCounty": "13S",
	"StreetTownName": "永丰街道",
	"StreetTownCode": "06Y",
	"GroupCode": "13S06Y"
}, {
	"ID": 168,
	"MembershipCounty": "13S",
	"StreetTownName": "石湖荡镇",
	"StreetTownCode": "07S",
	"GroupCode": "13S07S"
}, {
	"ID": 169,
	"MembershipCounty": "13S",
	"StreetTownName": "中山街道",
	"StreetTownCode": "08Z",
	"GroupCode": "13S08Z"
}, {
	"ID": 170,
	"MembershipCounty": "13S",
	"StreetTownName": "方松街道",
	"StreetTownCode": "09F",
	"GroupCode": "13S09F"
}, {
	"ID": 171,
	"MembershipCounty": "13S",
	"StreetTownName": "小昆山镇",
	"StreetTownCode": "10X",
	"GroupCode": "13S10X"
}, {
	"ID": 172,
	"MembershipCounty": "13S",
	"StreetTownName": "新桥镇",
	"StreetTownCode": "11X",
	"GroupCode": "13S11X"
}, {
	"ID": 173,
	"MembershipCounty": "13S",
	"StreetTownName": "广富林街道",
	"StreetTownCode": "12G",
	"GroupCode": "13S12G"
}, {
	"ID": 174,
	"MembershipCounty": "13S",
	"StreetTownName": "洞泾镇",
	"StreetTownCode": "13D",
	"GroupCode": "13S13D"
}, {
	"ID": 175,
	"MembershipCounty": "13S",
	"StreetTownName": "佘山镇",
	"StreetTownCode": "14S",
	"GroupCode": "13S14S"
}, {
	"ID": 176,
	"MembershipCounty": "13S",
	"StreetTownName": "九亭镇",
	"StreetTownCode": "15J",
	"GroupCode": "13S15J"
}, {
	"ID": 177,
	"MembershipCounty": "13S",
	"StreetTownName": "泗泾镇",
	"StreetTownCode": "16S",
	"GroupCode": "13S16S"
}, {
	"ID": 178,
	"MembershipCounty": "13S",
	"StreetTownName": "九里亭街道",
	"StreetTownCode": "17J",
	"GroupCode": "13S17J"
}, {
	"ID": 179,
	"MembershipCounty": "14Q",
	"StreetTownName": "练塘镇",
	"StreetTownCode": "01L",
	"GroupCode": "14Q01L"
}, {
	"ID": 180,
	"MembershipCounty": "14Q",
	"StreetTownName": "朱家角镇",
	"StreetTownCode": "02Z",
	"GroupCode": "14Q02Z"
}, {
	"ID": 181,
	"MembershipCounty": "14Q",
	"StreetTownName": "金泽镇",
	"StreetTownCode": "03J",
	"GroupCode": "14Q03J"
}, {
	"ID": 182,
	"MembershipCounty": "14Q",
	"StreetTownName": "徐泾镇",
	"StreetTownCode": "04X",
	"GroupCode": "14Q04X"
}, {
	"ID": 183,
	"MembershipCounty": "14Q",
	"StreetTownName": "赵巷镇",
	"StreetTownCode": "05Z",
	"GroupCode": "14Q05Z"
}, {
	"ID": 184,
	"MembershipCounty": "14Q",
	"StreetTownName": "夏阳街道",
	"StreetTownCode": "06X",
	"GroupCode": "14Q06X"
}, {
	"ID": 185,
	"MembershipCounty": "14Q",
	"StreetTownName": "盈浦街道",
	"StreetTownCode": "07Y",
	"GroupCode": "14Q07Y"
}, {
	"ID": 186,
	"MembershipCounty": "14Q",
	"StreetTownName": "华新镇",
	"StreetTownCode": "08H",
	"GroupCode": "14Q08H"
}, {
	"ID": 187,
	"MembershipCounty": "14Q",
	"StreetTownName": "重固镇",
	"StreetTownCode": "09C",
	"GroupCode": "14Q09C"
}, {
	"ID": 188,
	"MembershipCounty": "14Q",
	"StreetTownName": "香花桥街道",
	"StreetTownCode": "10X",
	"GroupCode": "14Q10X"
}, {
	"ID": 189,
	"MembershipCounty": "14Q",
	"StreetTownName": "白鹤镇",
	"StreetTownCode": "11B",
	"GroupCode": "14Q11B"
}, {
	"ID": 190,
	"MembershipCounty": "15F",
	"StreetTownName": "海湾镇",
	"StreetTownCode": "01H",
	"GroupCode": "15F01H"
}, {
	"ID": 191,
	"MembershipCounty": "15F",
	"StreetTownName": "柘林镇",
	"StreetTownCode": "02Z",
	"GroupCode": "15F02Z"
}, {
	"ID": 192,
	"MembershipCounty": "15F",
	"StreetTownName": "四团镇",
	"StreetTownCode": "03S",
	"GroupCode": "15F03S"
}, {
	"ID": 193,
	"MembershipCounty": "15F",
	"StreetTownName": "奉城镇",
	"StreetTownCode": "04F",
	"GroupCode": "15F04F"
}, {
	"ID": 194,
	"MembershipCounty": "15F",
	"StreetTownName": "青村镇",
	"StreetTownCode": "05Q",
	"GroupCode": "15F05Q"
}, {
	"ID": 195,
	"MembershipCounty": "15F",
	"StreetTownName": "金汇镇",
	"StreetTownCode": "06J",
	"GroupCode": "15F06J"
}, {
	"ID": 196,
	"MembershipCounty": "15F",
	"StreetTownName": "南桥镇",
	"StreetTownCode": "07N",
	"GroupCode": "15F07N"
}, {
	"ID": 197,
	"MembershipCounty": "15F",
	"StreetTownName": "庄行镇",
	"StreetTownCode": "08Z",
	"GroupCode": "15F08Z"
}, {
	"ID": 198,
	"MembershipCounty": "15F",
	"StreetTownName": "奉浦街道",
	"StreetTownCode": "09F",
	"GroupCode": "15F09F"
}, {
	"ID": 199,
	"MembershipCounty": "15F",
	"StreetTownName": "西渡街道",
	"StreetTownCode": "10X",
	"GroupCode": "15F10X"
}, {
	"ID": 200,
	"MembershipCounty": "16C",
	"StreetTownName": "横沙乡",
	"StreetTownCode": "01H",
	"GroupCode": "16C01H"
}, {
	"ID": 201,
	"MembershipCounty": "16C",
	"StreetTownName": "长兴镇",
	"StreetTownCode": "02C",
	"GroupCode": "16C02C"
}, {
	"ID": 202,
	"MembershipCounty": "16C",
	"StreetTownName": "上实现代农业园区",
	"StreetTownCode": "03S",
	"GroupCode": "16C03S"
}, {
	"ID": 203,
	"MembershipCounty": "16C",
	"StreetTownName": "东平镇",
	"StreetTownCode": "04D",
	"GroupCode": "16C04D"
}, {
	"ID": 204,
	"MembershipCounty": "16C",
	"StreetTownName": "陈家镇",
	"StreetTownCode": "05C",
	"GroupCode": "16C05C"
}, {
	"ID": 205,
	"MembershipCounty": "16C",
	"StreetTownName": "中兴镇",
	"StreetTownCode": "06Z",
	"GroupCode": "16C06Z"
}, {
	"ID": 206,
	"MembershipCounty": "16C",
	"StreetTownName": "向化镇",
	"StreetTownCode": "07X",
	"GroupCode": "16C07X"
}, {
	"ID": 207,
	"MembershipCounty": "16C",
	"StreetTownName": "堡镇",
	"StreetTownCode": "08P",
	"GroupCode": "16C08P"
}, {
	"ID": 208,
	"MembershipCounty": "16C",
	"StreetTownName": "港沿镇",
	"StreetTownCode": "09G",
	"GroupCode": "16C09G"
}, {
	"ID": 209,
	"MembershipCounty": "16C",
	"StreetTownName": "竖新镇",
	"StreetTownCode": "10S",
	"GroupCode": "16C10S"
}, {
	"ID": 210,
	"MembershipCounty": "16C",
	"StreetTownName": "新河镇",
	"StreetTownCode": "11X",
	"GroupCode": "16C11X"
}, {
	"ID": 211,
	"MembershipCounty": "16C",
	"StreetTownName": "城桥镇",
	"StreetTownCode": "12C",
	"GroupCode": "16C12C"
}, {
	"ID": 212,
	"MembershipCounty": "16C",
	"StreetTownName": "建设镇",
	"StreetTownCode": "13J",
	"GroupCode": "16C13J"
}, {
	"ID": 213,
	"MembershipCounty": "16C",
	"StreetTownName": "港西镇",
	"StreetTownCode": "14G",
	"GroupCode": "16C14G"
}, {
	"ID": 214,
	"MembershipCounty": "16C",
	"StreetTownName": "东平镇",
	"StreetTownCode": "15D",
	"GroupCode": "16C15D"
}, {
	"ID": 215,
	"MembershipCounty": "16C",
	"StreetTownName": "东平林场",
	"StreetTownCode": "16D",
	"GroupCode": "16C16D"
}, {
	"ID": 216,
	"MembershipCounty": "16C",
	"StreetTownName": "庙镇",
	"StreetTownCode": "17M",
	"GroupCode": "16C17M"
}, {
	"ID": 217,
	"MembershipCounty": "16C",
	"StreetTownName": "三星镇",
	"StreetTownCode": "18S",
	"GroupCode": "16C18S"
}, {
	"ID": 218,
	"MembershipCounty": "16C",
	"StreetTownName": "绿华镇",
	"StreetTownCode": "19L",
	"GroupCode": "16C19L"
}, {
	"ID": 219,
	"MembershipCounty": "16C",
	"StreetTownName": "新海镇",
	"StreetTownCode": "20X",
	"GroupCode": "16C20X"
}, {
	"ID": 220,
	"MembershipCounty": "16C",
	"StreetTownName": "新村乡",
	"StreetTownCode": "21X",
	"GroupCode": "16C21X"
}, {
	"ID": 221,
	"MembershipCounty": "06H",
	"StreetTownName": "北外滩街道",
	"StreetTownCode": "09B",
	"GroupCode": "06H09B"
}, {
	"ID": 222,
	"MembershipCounty": "09B",
	"StreetTownName": "绿化局",
	"StreetTownCode": "13L",
	"GroupCode": "09B13L"
}, {
	"ID": 223,
	"MembershipCounty": "11P",
	"StreetTownName": "六灶镇",
	"StreetTownCode": "37L",
	"GroupCode": "11P37L"
}, {
	"ID": 224,
	"MembershipCounty": "11P",
	"StreetTownName": "源深体育中心",
	"StreetTownCode": "38Y",
	"GroupCode": "11P38Y"
}, {
	"ID": 225,
	"MembershipCounty": "13S",
	"StreetTownName": "松江区体育局",
	"StreetTownCode": "18T",
	"GroupCode": "13S18T"
}, {
	"ID": 226,
	"MembershipCounty": "15F",
	"StreetTownName": "金海社区",
	"StreetTownCode": "11J",
	"GroupCode": "15F11J"
}, {
	"ID": 227,
	"MembershipCounty": "15F",
	"StreetTownName": "海湾旅游区",
	"StreetTownCode": "12H",
	"GroupCode": "15F12H"
}, {
	"ID": 228,
	"MembershipCounty": "09B",
	"StreetTownName": "宝山工业园区",
	"StreetTownCode": "13B",
	"GroupCode": "09B13B"
}]


/* 模拟的任务列表数据 */
export const taskList = [{
	"FacilitiesName": "新家园农民健身工程",
	"FacilitiesAddr": "农机路89弄",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "12H",
	"FacilitiesType": "QC",
	"FacilitiesTypeCode": "15F12HQCZJW0656",
	"Distance": ""
}, {
	"FacilitiesName": "上师大奉贤新院村健身点",
	"FacilitiesAddr": "奉炮公路432弄内",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "12H",
	"FacilitiesType": "JY",
	"FacilitiesTypeCode": "15F12HJYZJW0495",
	"Distance": ""
}, {
	"FacilitiesName": "文化新村健身点",
	"FacilitiesAddr": "奉炮公路157弄内",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "12H",
	"FacilitiesType": "JY",
	"FacilitiesTypeCode": "15F12HJYZJW0494",
	"Distance": ""
}, {
	"FacilitiesName": "新家园健身点",
	"FacilitiesAddr": "农机路89弄内",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "12H",
	"FacilitiesType": "JY",
	"FacilitiesTypeCode": "15F12HJYZJW0493",
	"Distance": ""
}, {
	"FacilitiesName": "海湾旅游区百姓健身房",
	"FacilitiesAddr": "奉炮公路141弄49号",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "12H",
	"FacilitiesType": "JF",
	"FacilitiesTypeCode": "15F12HJFZJW0683",
	"Distance": ""
}, {
	"FacilitiesName": "海湾旅游区健身步道",
	"FacilitiesAddr": "海湾路218号",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "12H",
	"FacilitiesType": "BD",
	"FacilitiesTypeCode": "15F12HBDZJW0551",
	"Distance": ""
}, {
	"FacilitiesName": "金海社区金水新苑农民工程篮球场",
	"FacilitiesAddr": "金海社区金齐路348弄",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "11J",
	"FacilitiesType": "QC",
	"FacilitiesTypeCode": "15F11JQCZJW0657",
	"Distance": ""
}, {
	"FacilitiesName": "金海社区南郊御墅健身点",
	"FacilitiesAddr": "德丰路250弄南郊御墅最西",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "11J",
	"FacilitiesType": "JY",
	"FacilitiesTypeCode": "15F11JJYZJW0500",
	"Distance": ""
}, {
	"FacilitiesName": "金海社区金水丽苑健身点",
	"FacilitiesAddr": "嘉园路361弄26号附近",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "11J",
	"FacilitiesType": "JY",
	"FacilitiesTypeCode": "15F11JJYZJW0499",
	"Distance": ""
}, {
	"FacilitiesName": "金海社区恒贤居委健身点",
	"FacilitiesAddr": "德丰路199弄40-41号之间",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "11J",
	"FacilitiesType": "JY",
	"FacilitiesTypeCode": "15F11JJYZJW0498",
	"Distance": ""
}, {
	"FacilitiesName": "金海社区恒盛泽丰路89号健身点",
	"FacilitiesAddr": "泽丰路89弄靠近钟楼",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "11J",
	"FacilitiesType": "JY",
	"FacilitiesTypeCode": "15F11JJYZJW0497",
	"Distance": ""
}, {
	"FacilitiesName": "金海社区金水佳苑健身苑点",
	"FacilitiesAddr": "金海社区广丰路100弄",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "11J",
	"FacilitiesType": "JY",
	"FacilitiesTypeCode": "15F11JJYZJW0496",
	"Distance": ""
}, {
	"FacilitiesName": "金海社区百姓健身房",
	"FacilitiesAddr": "金海社区广丰路100号",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "11J",
	"FacilitiesType": "JF",
	"FacilitiesTypeCode": "15F11JJFZJW0684",
	"Distance": ""
}, {
	"FacilitiesName": "金海社区金水苑健身点",
	"FacilitiesAddr": "金海社区金齐路188弄",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "11J",
	"FacilitiesType": "JD",
	"FacilitiesTypeCode": "15F11JJDZJW0371",
	"Distance": ""
}, {
	"FacilitiesName": "金海社区恒盛湖畔豪庭262弄健身点",
	"FacilitiesAddr": "金海社区泽丰路262弄",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "11J",
	"FacilitiesType": "JD",
	"FacilitiesTypeCode": "15F11JJDZJW0370",
	"Distance": ""
}, {
	"FacilitiesName": "金海社区恒盛湖畔豪庭88弄健身点",
	"FacilitiesAddr": "金海社区泽丰路88弄",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "11J",
	"FacilitiesType": "JD",
	"FacilitiesTypeCode": "15F11JJDZJW0369",
	"Distance": ""
}, {
	"FacilitiesName": "金海社区金水新苑健身苑点",
	"FacilitiesAddr": "金海社区金齐路348弄",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "11J",
	"FacilitiesType": "JD",
	"FacilitiesTypeCode": "15F11JJDZJW0368",
	"Distance": ""
}, {
	"FacilitiesName": "金海社区金水丽苑BD",
	"FacilitiesAddr": "嘉园路361弄26号附近",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "11J",
	"FacilitiesType": "BD",
	"FacilitiesTypeCode": "15F11JBDZJW0554",
	"Distance": ""
}, {
	"FacilitiesName": "金海社区金水新苑百姓健身步道",
	"FacilitiesAddr": "金海社区金齐路348弄",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "11J",
	"FacilitiesType": "BD",
	"FacilitiesTypeCode": "15F11JBDZJW0553",
	"Distance": ""
}, {
	"FacilitiesName": "金海社区金水佳苑百姓健身步道",
	"FacilitiesAddr": "金海社区金水佳苑广丰路100号",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "11J",
	"FacilitiesType": "BD",
	"FacilitiesTypeCode": "15F11JBDZJW0552",
	"Distance": ""
}, {
	"FacilitiesName": "灯塔村农民体育健身工程",
	"FacilitiesAddr": "灯塔村农家会所",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "QC",
	"FacilitiesTypeCode": "15F10XQCZJW0669",
	"Distance": ""
}, {
	"FacilitiesName": "益民村农民体育健身工程",
	"FacilitiesAddr": "益民村5组",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "QC",
	"FacilitiesTypeCode": "15F10XQCZJW0668",
	"Distance": ""
}, {
	"FacilitiesName": "金港村农民体育健身工程",
	"FacilitiesAddr": "奉金路延伸段",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "QC",
	"FacilitiesTypeCode": "15F10XQCZJW0667",
	"Distance": ""
}, {
	"FacilitiesName": "南渡村农民体育健身工程",
	"FacilitiesAddr": "西闸公路901弄300号",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "QC",
	"FacilitiesTypeCode": "15F10XQCZJW0666",
	"Distance": ""
}, {
	"FacilitiesName": "关港村农民体育健身工程",
	"FacilitiesAddr": "关港村村委会",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "QC",
	"FacilitiesTypeCode": "15F10XQCZJW0665",
	"Distance": ""
}, {
	"FacilitiesName": "北新村农民体育健身工程",
	"FacilitiesAddr": "西闸公路568号北新村村委会",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "QC",
	"FacilitiesTypeCode": "15F10XQCZJW0664",
	"Distance": ""
}, {
	"FacilitiesName": "五宅村农民体育健身工程",
	"FacilitiesAddr": "五宅村538号",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "QC",
	"FacilitiesTypeCode": "15F10XQCZJW0663",
	"Distance": ""
}, {
	"FacilitiesName": "发展村农民体育健身工程",
	"FacilitiesAddr": "发展村村委会",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "QC",
	"FacilitiesTypeCode": "15F10XQCZJW0662",
	"Distance": ""
}, {
	"FacilitiesName": "益民村社区公共运动场",
	"FacilitiesAddr": "益民村村委会",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "QC",
	"FacilitiesTypeCode": "15F10XQCZJW0661",
	"Distance": ""
}, {
	"FacilitiesName": "灯塔村社区公共运动场",
	"FacilitiesAddr": "灯塔村村委会",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "QC",
	"FacilitiesTypeCode": "15F10XQCZJW0660",
	"Distance": ""
}, {
	"FacilitiesName": "西渡社区公共运动场",
	"FacilitiesAddr": "扶港路1150号",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "QC",
	"FacilitiesTypeCode": "15F10XQCZJW0659",
	"Distance": ""
}, {
	"FacilitiesName": "新南家园社区公共运动场",
	"FacilitiesAddr": "新南家园内",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "QC",
	"FacilitiesTypeCode": "15F10XQCZJW0658",
	"Distance": ""
}, {
	"FacilitiesName": "锦港新村市民益智健身点",
	"FacilitiesAddr": "锦港新村5幢13-15号",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "JY",
	"FacilitiesTypeCode": "15F10XJYZJW0511",
	"Distance": ""
}, {
	"FacilitiesName": "关港村市民益智健身点",
	"FacilitiesAddr": "关港村",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "JY",
	"FacilitiesTypeCode": "15F10XJYZJW0510",
	"Distance": ""
}, {
	"FacilitiesName": "发展村市民益智健身点",
	"FacilitiesAddr": "发展村村委会",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "JY",
	"FacilitiesTypeCode": "15F10XJYZJW0509",
	"Distance": ""
}, {
	"FacilitiesName": "澳洲国际市民益智健身点",
	"FacilitiesAddr": "澳洲国际内水岸家苑82号旁",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "JY",
	"FacilitiesTypeCode": "15F10XJYZJW0508",
	"Distance": ""
}, {
	"FacilitiesName": "水岸家苑市民益智健身点",
	"FacilitiesAddr": "水岸家苑内13幢37-40号",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "JY",
	"FacilitiesTypeCode": "15F10XJYZJW0507",
	"Distance": ""
}, {
	"FacilitiesName": "鸿宝三居市民益智健身点",
	"FacilitiesAddr": "鸿宝二村47幢419-422号",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "JY",
	"FacilitiesTypeCode": "15F10XJYZJW0506",
	"Distance": ""
}, {
	"FacilitiesName": "扶兰新村市民益智健身点",
	"FacilitiesAddr": "扶兰小区内",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "JY",
	"FacilitiesTypeCode": "15F10XJYZJW0505",
	"Distance": ""
}, {
	"FacilitiesName": "大桥公寓市民益智健身点",
	"FacilitiesAddr": "大桥小区西闸路1187号",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "JY",
	"FacilitiesTypeCode": "15F10XJYZJW0504",
	"Distance": ""
}, {
	"FacilitiesName": "西渡社区市民益智健身苑",
	"FacilitiesAddr": "扶港路1150号",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "JY",
	"FacilitiesTypeCode": "15F10XJYZJW0503",
	"Distance": ""
}, {
	"FacilitiesName": "北新村市民益智健身点",
	"FacilitiesAddr": "北新村村委",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "JY",
	"FacilitiesTypeCode": "15F10XJYZJW0502",
	"Distance": ""
}, {
	"FacilitiesName": "金都雅苑市民益智健身点",
	"FacilitiesAddr": "金都雅苑26幢87号旁",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "JY",
	"FacilitiesTypeCode": "15F10XJYZJW0501",
	"Distance": ""
}, {
	"FacilitiesName": "灯塔百姓游泳健身房",
	"FacilitiesAddr": "沪杭公路425号大同路路口",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "JF",
	"FacilitiesTypeCode": "15F10XJFZJW0685",
	"Distance": ""
}, {
	"FacilitiesName": "益民村健身点",
	"FacilitiesAddr": "红专活动场653号",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "JD",
	"FacilitiesTypeCode": "15F10XJDZJW0395",
	"Distance": ""
}, {
	"FacilitiesName": "紫菊新苑健身点",
	"FacilitiesAddr": "紫菊新苑1358弄15号",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "JD",
	"FacilitiesTypeCode": "15F10XJDZJW0394",
	"Distance": ""
}, {
	"FacilitiesName": "南渡村大同小区健身点",
	"FacilitiesAddr": "大同小区944号前",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "JD",
	"FacilitiesTypeCode": "15F10XJDZJW0393",
	"Distance": ""
}, {
	"FacilitiesName": "碧瑶别墅健身点",
	"FacilitiesAddr": "扶栏路118弄碧瑶别墅7号房西侧小花园",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "JD",
	"FacilitiesTypeCode": "15F10XJDZJW0392",
	"Distance": ""
}, {
	"FacilitiesName": "五宅村健身点",
	"FacilitiesAddr": "五宅村内",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "JD",
	"FacilitiesTypeCode": "15F10XJDZJW0391",
	"Distance": ""
}, {
	"FacilitiesName": "金港村健身点",
	"FacilitiesAddr": "金光老年茶室前",
	"Coordinate": "",
	"PanoramicPhoto": "",
	"MembershipCounty": "15F",
	"StreetTownName": "10X",
	"FacilitiesType": "JD",
	"FacilitiesTypeCode": "15F10XJDZJW0390",
	"Distance": ""
}]

/* 模拟任务详情 */
export const taskDetail = {
	"FacilitiesName": "银河新都健身苑点A",
	"FacilitiesAddr": "绿莲路99弄",
	"Coordinate": "{\"longitude\":\"121.420069\",\"latitude\":\"31.101168\"}",
	"PanoramicPhoto": "http://operation.esplohas.com",
	"MembershipCounty": "闵行区",
	"StreetTownName": "梅陇镇",
	"FacilitiesType": "传统健身苑点",
	"FacilitiesTypeCode": "08M08MJDZJW7101",
	"ConstructionProperty": "市建",
	"CompletionTime": "2005-02-01T00:00:00",
	"ActivityArea": 150,
	"EqInfo": [{
		"InstrumentName": "呼啦盘",
		"InstrumentImage": "http://operation.esplohas.com"
	}, {
		"InstrumentName": "双人太空漫步器",
		"InstrumentImage": "http://operation.esplohas.com"
	}, {
		"InstrumentName": "腹背锻炼器",
		"InstrumentImage": "http://operation.esplohas.com"
	}, {
		"InstrumentName": "三人上肢牵引器",
		"InstrumentImage": "http://operation.esplohas.com"
	}, {
		"InstrumentName": "压腿杠",
		"InstrumentImage": "http://operation.esplohas.com"
	}, {
		"InstrumentName": "健骑器",
		"InstrumentImage": "http://operation.esplohas.com"
	}, {
		"InstrumentName": "太极云手",
		"InstrumentImage": "http://operation.esplohas.com"
	}, {
		"InstrumentName": "下肢康复器",
		"InstrumentImage": "http://operation.esplohas.com"
	}]
}


export default {
	countryList,
	streetTowns,
	taskList,
	taskDetail
}
